config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :conversations
    resources :reviews
    resources :listings
    resources :messages
    resources :notifications
    resources :photos
    resources :reservations
    resources :guest_reviews
    resources :host_reviews

    root to: "users#index"
  end

  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }


  resources :users, only: [:show, :index] do
    member do

      post '/verify_phone_number' => 'users#verify_phone_number'

      patch '/update_phone_number' => 'users#update_phone_number'

      patch '/update_license' => 'users#update_license'

      patch '/update_bank_account' => 'users#update_bank_account'

      patch '/update_image' => 'users#update_image'


    end
  end


  get '/crop_image' => "users#crop_image"

  get '/certification' => "users#certification"

  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"


  resources :listings, except: [:edit] do
    member do


      get 'information'
      get 'photo_upload'
      get 'detail'
      get 'exhibition'

      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :show]
  end




  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/my_reservations' => 'reservations#my_reservations'
  get '/guest_reservations' => 'reservations#guest_reservations'

  get 'search' => 'pages#search'

  get '/ajaxsearch' => 'pages#ajaxsearch'

  get 'index' => 'pages#index'
  get 'refer' => 'pages#refer'




  # ---- AirKong ------
  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
     post '/approve' => "reservations#approve"
     post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end



  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  # オリジナル追加
  get 'about' => 'pages#about'

  get 'pages/management' => 'pages#management'
  get 'pages/guide' => 'pages#guide'
  get 'pages/legal' => 'pages#legal'
  get 'pages/rules' => 'pages#rules'
  get 'pages/policy' => 'pages#policy'
  get 'pages/host_flow' => 'pages#host_flow'
  get 'pages/guest_flow' => 'pages#guest_flow'
  get 'pages/qanda' => 'pages#qanda'



  get 'inquiry' => 'inquiry#index'
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  get 'entry' => 'entry#index'
  get 'entry/confirm' => redirect("/entry")
  get 'entry/thanks' => redirect("/entry")
  post 'entry/confirm' => 'entry#confirm'
  post 'entry/thanks' => 'entry#thanks'

  get 'apply' => 'apply#index'
  get 'apply/confirm' => redirect("/apply")
  get 'apply/thanks' => redirect("/apply")
  post 'apply/confirm' => 'apply#confirm'
  post 'apply/thanks' => 'apply#thanks'

  get 'notice' => 'pages#notice'

  resources :fees, only: [:index]
end

app/models/listing.rb
class Listing < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}

  belongs_to :user
  has_many :photos , dependent: :destroy
  has_many :reservations, dependent: :destroy

  has_many :guest_reviews, dependent: :destroy


  # 緯度経度取得
  geocoded_by :location

  after_validation :geocode, if: :location_changed?

  validates :listing_type, presence: true
  validates :category1, presence: true
  validates :category2, presence: true
  validates :listing_title, presence: true
  validates :price_day, presence: true

  # カンマ削除
  before_save :price_day
  before_save :purchase_price



  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else

       "blank.jpg"

    end
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end

  def price_day=(num)
    num.gsub!(',','') if num.is_a?(String)
    self[:price_day] = num.to_i
  end

  def purchase_price=(num)
    num.gsub!(',','') if num.is_a?(String)
    self[:purchase_price] = num.to_i
  end

end

app/controllers/admin/listings_controller.rb
module Admin
  class ListingsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Listing.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Listing.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def display_resource(user)
      fullname = user.fullname
    end

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]

  before_action :is_authorised, only: [ :exhibition, :information, :detail, :photo_upload, :update]

  include ActionView::Helpers::UrlHelper



  def index
    @listings = current_user.listings.includes( :photos)

  end

  def show

    @photos = @listing.photos
    @guest_reviews = @listing.guest_reviews.includes( :guest)
  end

  def new
    if !current_user.phone_verified
     flash[:alert] = "電話番号の認証が必要です"
     return redirect_to certification_path
    elsif !current_user.license_file_name
     flash[:alert] = "身分証明書の登録が必要です"
     return redirect_to certification_path

    elsif

     current_user.fullname.nil? ||
     current_user.nickname.nil? ||

     current_user.address_zipcode.nil? ||
     current_user.address_prefecture_name.nil? ||
     current_user.description.nil?

     return redirect_to edit_user_registration_path, alert: "プロフィールの登録をお願いします"

    elsif

    !current_user.image_file_name

    return redirect_to edit_user_registration_path, alert: "プロフィール画像を変更してください"

    else
     @user = current_user
     @listing = current_user.listings.build
     @photos = @listing.photos
    end
  end


  def create
    @listing = current_user.listings.build(listing_params)

    @photos = @listing.photos
     if @listing.save
      redirect_to photo_upload_listing_path(@listing), notice: "商品情報の登録が終わりました、次は画像を登録しましょう"

      ListingMailer.send_email_to_host(@listing).deliver

     else
      flash[:alert] = "登録がうまくいきませんでした"
      render :new
     end
  end

  def exhibition
  end

  def information
    @listing = Listing.find(params[:id])
    @user = User.find(@listing.user_id)
  end

  def photo_upload
    @photos = @listing.photos

  end

  def detail
    @listing = Listing.find(params[:id])
    @user = User.find(@listing.user_id)
  end


  def update
    new_params = listing_params


    if @listing.update(new_params)

       if @listing.active.blank?
        redirect_to exhibition_listing_path(@listing), notice: "商品を編集しました"

       else
         flash[:notice] = "商品を編集しました"

         redirect_back(fallback_location: request.referer)
       end

    else
      flash[:alert] = "商品の編集がうまくいきませんでした"
      redirect_back(fallback_location: request.referer)
    end


  end

  def destroy
    @listing = Listing.find(params[:id])

    @listing.destroy
    flash[:notice] = "商品を削除しました"

    redirect_back(fallback_location: request.referer)
  end

  # 予約フォーム
  def preload
    today = Date.today
    reservations = @listing.reservations.where("(start_date >= ? OR end_date >= ?) AND status = ?", today, today, 1)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @listing)
    }

    render json: output
  end



  private
  def is_conflict(start_date, end_date, listing)
    check = listing.reservations.where("(? < start_date AND end_date < ?) AND status = ?", start_date, end_date, 1)
    check.size > 0? true : false
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def is_authorised
    redirect_to root_path, alert: "このページを編集する権限がありません" unless current_user.id == @listing.user_id
  end



  def is_ready_listing
    !@listing.active && !@listing.price_day.blank? && !@listing.photos.blank?
  end

  def listing_params
    params.require(:listing).permit(:listing_title, :listing_type, :category1, :category2,  :price, :price_per,  :price_hour, :price_day, :price_month, :description, :location, :is_shower, :is_bicycle, :is_wetsuit, :purchase_price, :purchase_time, :active, :instant)
  end

end

app/views/listings/_listing_menu.html.erb
<div class="row listing-menu ">
  <div class="col-md-8 col-md-offset-2">
    <ul class="">
      <li class="listing-item">
        <%= link_to "商品の基本情報", information1_listing_path, class: "listing-link active blue" %>
        <span class="blue"><i class="fa fa-check"></i></span>
      </li>
      <li class="listing-item">

        <% if !@listing.description.blank? %>
        <%= link_to "商品の詳細", information2_listing_path, class: "listing-link active blue" %>
        <span class="blue"><i class="fa fa-check"></i></span>
        <% else %>
        <%= link_to "商品の詳細", information2_listing_path, class: "listing-link active text-gray" %>
        <span class="text-gray"><i class="fa fa-check"></i></span>
        <% end %>
      </li>
      <li class="listing-item">

        <% if !@listing.photos.blank? %>

        <%= link_to "画像のアップロード", photo_upload_listing_path, class: "listing-link active blue" %>
        <span id='photo_check' class=" blue"><i class="fa fa-check"></i></span>
        <% else %>

        <%= link_to "画像のアップロード", photo_upload_listing_path, class: "listing-link active text-gray" %>
        <span class=" text-gray"><i class="fa fa-check"></i></span>
        <% end %>
      </li>

    </ul>


    <p>
      <% is_ready = !@listing.active && !@listing.description.blank? && !@listing.photos.blank?  %>

      <%= form_for @listing do |f| %>
        <%= f.hidden_field :active, value: true %>
        <%= f.submit "公開する", class:  'btn-sm  white b-green', disabled: !is_ready %>
      <% end %>
    </p>
    


  </div>
</div>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
削除

app/views/listings/detail.html.erb
<% if @listing.active.blank? %>
  <div class="registration-alert b-light-red">
    <p>
      まだ公開されていません&nbsp;
      <%= link_to "公開する", exhibition_listing_path(@listing) , class: "blue b-white" %>
    </p>
  </div>
<% end %>
<% if !@listing.active.blank?  %>
  <div class="dashboard-link">
  <ul class="">

    <li class=""><%= link_to "基本情報の編集",  information_listing_path(@listing) %></li>
    <li class=""><%= link_to "画像アップロード",  photo_upload_listing_path(@listing)  %></li>
    <li class="active"><%= link_to "詳細情報の編集",  photo_upload_listing_path(@listing)  %></li>

  </ul>
</div>
  <div class="registration-alert b-light-green">
    <p>公開中</p>
  </div>

<% end %>

<div class="row">
  <div class=" text-center">
    <div class="panel panel-default">
      <h3>
        <b>
          <% if @listing.active.blank? %>
           <span class="blue">ステップ3</span>
           詳細情報を入力
          <% else %>
           詳細情報の編集
          <% end %>
        </b>

      </h3>

      <p class="b-blue  listing-title">

        <%= link_to @listing.listing_title, listing_path(@listing) , class: "white" %>

      </p>

      <div class="container">
        <%= form_for @listing,html: {multipart: true} do |f| %>

        <% if @listing.category1 == "サーフボード" || @listing.category1 == "SUPボード" %>
         <div class="form_box">
          <p><b>ブランド</b></p>
          <div class="form-group">
            <%= f.text_field :brand, placeholder: "例:CHANNEL ISLANDS、CATCH SURF、オーダーメイド", class: "form-control", required: true %>
          </div>
         </div>

         <div class="form_box">
          <p><b>サイズ</b></p>
          <div class="form-group">
            <%= f.text_field :purchase_time, placeholder: "長さ213.3cm×幅55.8cm×厚さ7,6cm", class: "form-control" , required: true%>
          </div>
         </div>
        <% end %>


        <div class="form_box">
          <p><b>商品の詳細説明</b></p>
          <div class="form-group">
            <%= f.text_area :description, rows: 5, placeholder: "例:昨年の夏に購入しました。湘南の波にピッタリで、上級者からビギナーまで楽しめます。シングルフィン、リシューコード付き、サイズ7'0×22×3 1/8", class: "form-control", required: true %>
          </div>
        </div>

        <div class="form_box">
          <p><b>利用可能なアメニティ</b></p>
          <div class="form-group row">
            <div class="col-md-4 col-sm-4 col-xs-4 check">
              <%= f.check_box :is_shower %>
              シャワー
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4 check">
              <%= f.check_box :is_bicycle %>
              自転車
            </div>

             <div class="col-md-4 col-sm-4 col-xs-4 check">
               <%= f.check_box :is_wetsuit %>
              ウェットスーツ
             </div>

          </div>
        </div>


        <div class="form_box">
          <p><b>出品価格</b></p>
          <div class="" id="information-price">

            <div class="form-group" >
              <ul class="row">
                <li id="price_day-margin">
                  <p>1日</p>
                </li>
                <li class="">
                  <%= f.text_field :price_day, placeholder: "例:3000", class: "form-control", required: true %>
                </li>
                <li class="">
                  <p>円</p>
                </li>
              </ul>
            </div>

          </div>

        </div>


        <div class="purchase">
          <p class="text-left">
            ※ボード類を出品する場合は入力してください(破損が起きた際の補償費の計算の参考にします)
          </p>

          <div class="form_box">
            <p><b>購入時期</b></p>
            <div class="form-group">
              <%= f.text_field :purchase_time, placeholder: "例:2016年春ごろ", class: "form-control" %>
            </div>
          </div>

          <div class="form_box">
            <p><b>購入価格</b></p>
            <div class="">

              <div class="form-group" >
                <ul class="row">

                  <li class="">
                    <%= f.text_field :purchase_price, placeholder: "例:80000", class: "form-control" %>
                  </li>
                  <li class="">
                    <p>円</p>
                  </li>
                </ul>
              </div>

            </div>

          </div>

          </div>
        </div>


        <%= f.hidden_field :listing_type, value: "レンタル"  %>
        <%= f.hidden_field :location, value: @user.address_city %>
        <%= f.hidden_field :instant, value: "Request" %>

        <div class="actions">
          <%= f.submit "編集する", class: "btn btn-form" %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

<script type="text/javascript">
$(document).ready(function(){

  var $children = $('.children'); //カテゴリー2の要素を変数に入れます。
  var original = $children.html(); //後のイベントで、不要なoption要素を削除するため、オリジナルをとっておく

  //カテゴリー1のselect要素が変更になるとイベントが発生
  $('.parent').change(function() {
    //選択されたカテゴリー1のvalueを取得し変数に入れる
    var val1 = $(this).val();

    //削除された要素をもとに戻すため.html(original)を入れておく
    $children.html(original).find('option').each(function() {
      var val2 = $(this).data('val'); //data-valの値を取得

      //valueと異なるdata-valを持つ要素を削除
      if (val1 != val2) {
        $(this).not(':first-child').remove();
      }

    });

    //カテゴリー1のselect要素が未選択の場合、カテゴリー2をdisabledにする
    if ($(this).val() !== "") {
      $children.fadeIn(100);
    } else {
      $children.fadeOut(100);
    }

  });


});
</script>

app/views/listings/index.html.erb
<div class="dashboard-link">
  <ul class="">
    <li class="active"><%= link_to "貸出しアイテム", listings_path %></li>
    <li class=""><%= link_to "貸出し履歴",  guest_reservations_path %></li>
    <li class=""><%= link_to "振込先", payout_method_path %></li>
  </ul>
</div>

<div class="row listing-index">
  <div class="col-md-8 col-md-offset-2">
    <div class="">
      <h3>
        <b>
          貸出しアイテム
        </b>

      </h3>

      <div class="">
        <% if @listings.count == 0 %>
         <p>まだ出品中のアイテムがありません</p><br/>
         <%= link_to "出品する", new_listing_path, class: "btn btn-form" %>

        <% else %>

         <% @listings.each do |listing| %>
          <div class="box">
            <p>
              <%= listing.created_at.strftime('%Y年%m月%d日') %>登録
            </p>

            <div class="bottom">
              <ul class="row">
                <li class="col-md-6 col-sm-6 col-xs-6">
                  <%= image_tag listing.cover_photo(:thumb) %>
                </li>
                <li class="col-md-6 col-sm-6 col-xs-6">
                  <p>
                    <%= link_to listing.listing_title, listing_path(listing) %>
                    <% if !listing.active.blank? %>
                     <span class="white b-light-green ">
                      公開中
                     </span>
                    <% end %>
                  </p>
                  <p>
                    <span>
                      <%= link_to "編集", information_listing_path(listing) , class: "btn-sm white b-orange" %>
                    </span>
                    <span>
                      <%= link_to  listing_path(listing),  class: "btn-sm white b-gray", method: :delete, data: {confirm: "削除しても大丈夫ですか?"} do %>
                        削除
                      <% end %>
                    </span>

                  </p>

                  <p>
                    <span>
                     <% if !listing.active || listing.active == false %>

                        <%= form_for listing do |f| %>
                         <%= f.hidden_field :active, value: true %>
                         <%= f.submit "公開する", class:  'btn-xs  white b-green' %>
                        <% end %>

                     <% else
                       listing.active == true  %>

                        <%= form_for listing do |f| %>
                         <%= f.hidden_field :active, value: false %>
                         <%= f.submit "公開停止", class:  'btn-xs white b-gray' %>
                        <% end %>


                     <% end %>
                    </span>
                  </p>



                </li>
              </ul>
            </div>


          </div>
         <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listings/information.html.erb
<% if @listing.active.blank? %>
  <div class="registration-alert b-light-red">
    <p>
      まだ公開されていません&nbsp;
      <%= link_to "公開する", exhibition_listing_path(@listing) , class: "blue b-white" %>
    </p>
  </div>
<% end %>
<% if !@listing.active.blank?  %>
  <div class="dashboard-link">
  <ul class="">

    <li class="active"><%= link_to "商品の編集",  information_listing_path(@listing) %></li>
    <li class=""><%= link_to "画像アップロード",  photo_upload_listing_path(@listing)  %></li>

  </ul>
</div>
  <div class="registration-alert b-light-green">
    <p>公開中</p>
  </div>

<% end %>

<div class="row">
  <div class=" text-center">
    <div class="panel panel-default">
      <h3>
        <b>
          <% if @listing.active.blank? %>
           <span class="blue">ステップ1</span>
           商品情報を入力
          <% else %>
           商品の編集
          <% end %>
        </b>

      </h3>

      <p class="b-blue  listing-title">

        <%= link_to @listing.listing_title, listing_path(@listing) , class: "white" %>

      </p>

      <div class="container">
        <%= form_for @listing,html: {multipart: true} do |f| %>

        <div class="form_box">
          <p><b>カテゴリー</b></p>
          <div class="form-group">
           <%= f.select :category1,
           [["サーフボード", "サーフボード"],
            ["SUPボード", "SUPボード"],
            ["その他", "その他"]],


            {prompt:"カテゴリー1"},
            {required: true, autofocus: 'true', class: "form-control parent",id: "category1"}
            %>
          </div>

          <div class="form-group">
           <%= f.select :category2,
           [["ショートボード", "ショートボード", data: {val:"サーフボード"}],
            ["ファンボード", "ファンボード", data: {val:"サーフボード"}],
            ["ロングボード", "ロングボード", data: {val:"サーフボード"}],
            ["サーフ", "サーフ", data: {val:"SUPボード"}],
            ["オールラウンド", "オールラウンド", data: {val:"SUPボード"}],
            ["フィッシング", "フィッシング", data: {val:"SUPボード"}],
            ["クルージング", "クルージング", data: {val:"SUPボード"}],
            ["コーチング", "コーチング", data: {val:"その他"}],
            ["ボード置き場", "ボード置き場", data: {val:"その他"}],
            ["写真撮影", "写真撮影", data: {val:"その他"}]],


            {prompt: "カテゴリー2"},
            {required: true, autofocus: 'true', class: "form-control children",id: "category2"}
            %>
          </div>
        </div>

        <div class="form_box">
          <p><b>商品名</b></p>
          <div class="form-group">
            <%= f.text_field :listing_title, placeholder: "例:キャッチサーフのファンボード", class: "form-control", required: true %>
          </div>
        </div>

        <div class="form_box">
          <p><b>商品の詳細説明</b></p>
          <div class="form-group">
            <%= f.text_area :description, rows: 5, placeholder: "例:昨年の夏に購入しました。湘南の波にピッタリで、上級者からビギナーまで楽しめます。シングルフィン、リシューコード付き、サイズ7'0×22×3 1/8", class: "form-control", required: true %>
          </div>
        </div>

        <div class="form_box">
          <p><b>利用可能なアメニティ</b></p>
          <div class="form-group row">
            <div class="col-md-4 col-sm-4 col-xs-4 check">
              <%= f.check_box :is_shower %>
              シャワー
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4 check">
              <%= f.check_box :is_bicycle %>
              自転車
            </div>

             <div class="col-md-4 col-sm-4 col-xs-4 check">
               <%= f.check_box :is_wetsuit %>
              ウェットスーツ
             </div>

          </div>
        </div>


        <div class="form_box">
          <p><b>出品価格</b></p>
          <div class="" id="information-price">

            <div class="form-group" >
              <ul class="row">
                <li id="price_day-margin">
                  <p>1日</p>
                </li>
                <li class="">
                  <%= f.text_field :price_day, placeholder: "例:3000", class: "form-control", required: true %>
                </li>
                <li class="">
                  <p>円</p>
                </li>
              </ul>
            </div>

          </div>

        </div>


        <div class="purchase">
          <p class="text-left">
            ※ボード類を出品する場合は入力してください(破損が起きた際の補償費の計算の参考にします)
          </p>

          <div class="form_box">
            <p><b>購入時期</b></p>
            <div class="form-group">
              <%= f.text_field :purchase_time, placeholder: "例:2016年春ごろ", class: "form-control" %>
            </div>
          </div>

          <div class="form_box">
            <p><b>購入価格</b></p>
            <div class="">

              <div class="form-group" >
                <ul class="row">

                  <li class="">
                    <%= f.text_field :purchase_price, placeholder: "例:80000", class: "form-control" %>
                  </li>
                  <li class="">
                    <p>円</p>
                  </li>
                </ul>
              </div>

            </div>

          </div>

          </div>
        </div>


        <%= f.hidden_field :listing_type, value: "レンタル"  %>
        <%= f.hidden_field :location, value: @user.address_city %>
        <%= f.hidden_field :instant, value: "Request" %>

        <div class="actions">
          <%= f.submit "編集する", class: "btn btn-form" %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#autoaddress").geocomplete();
  })
</script>

<script type="text/javascript">
$(document).ready(function(){

  var $children = $('.children'); //カテゴリー2の要素を変数に入れます。
  var original = $children.html(); //後のイベントで、不要なoption要素を削除するため、オリジナルをとっておく

  //カテゴリー1のselect要素が変更になるとイベントが発生
  $('.parent').change(function() {
    //選択されたカテゴリー1のvalueを取得し変数に入れる
    var val1 = $(this).val();

    //削除された要素をもとに戻すため.html(original)を入れておく
    $children.html(original).find('option').each(function() {
      var val2 = $(this).data('val'); //data-valの値を取得

      //valueと異なるdata-valを持つ要素を削除
      if (val1 != val2) {
        $(this).not(':first-child').remove();
      }

    });

    //カテゴリー1のselect要素が未選択の場合、カテゴリー2をdisabledにする
    if ($(this).val() !== "") {
      $children.fadeIn(100);
    } else {
      $children.fadeOut(100);
    }

  });


});
</script>

app/views/listings/photo_upload.html.erb
<% if @listing.active.blank? %>
  <div class="registration-alert b-light-red">
    <p>
      まだ公開されていません&nbsp;
      <%= link_to "公開する", exhibition_listing_path(@listing), class: "blue b-white"  %>
    </p>
  </div>
<% end %>
<% if !@listing.active.blank?  %>
  <div class="dashboard-link">
  <ul class="">

    <li class=""><%= link_to "商品の編集",  information_listing_path(@listing) %></li>
    <li class="active"><%= link_to "画像アップロード",  photo_upload_listing_path(@listing)  %></li>

  </ul>
</div>
  <div class="registration-alert b-light-green">
    <p>公開中</p>
  </div>

<% end %>

<div class="row" >
  <div class=" text-center">
    <div class="panel panel-default">
      <h3>
        <b>
          <% if @listing.active.blank?  %>
            <span class="blue">ステップ2</span>
          <% end %>
          画像アップロード
        </b>

      </h3>

      <p class="b-blue  listing_title">

        <%= link_to @listing.listing_title, listing_path(@listing) , class: "white" %>

      </p>

      <div class="panel-body">
        <div class="container">

          <div id="photos">
            <%= render 'photos/photos_list' %>
          </div>


          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @listing, url: listing_photos_path(@listing), method: 'post', html: {multipart: true} do |f| %>

                <div class="row" id="photos-select">
                  <div class="form-group">
                    <span class="btn btn-default btn-file">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i>画像を選択

                      <%= file_field_tag "images[]", type: :file, multiple: true , id: "pictureInput" %>

                    </span>
                  </div>
                </div>

                <div class="photo-preview">
                  <p class="text-center">
                    プレビュー
                  </p>
                  <div id="target">
                  </div>

                  <div class="text-center">
                    <%= f.submit "アップロード", class: "btn btn-form" %>
                  </div>

                </div>


              <% end %>



              <script type="text/javascript">
              $(function() {
                $('#pictureInput').on('change', function(event) {
                  var files = event.target.files;
                  var image = files[0]
                  var reader = new FileReader();
                  reader.onload = function(file) {
                    var img = new Image();
                    console.log(file);
                    img.src = file.target.result;
                    $('#target').html(img);
                  }
                  reader.readAsDataURL(image);
                  console.log(files);
                });
              });


              </script>


            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>