config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :conversations
    resources :reviews
    resources :listings
    resources :messages
    resources :notifications
    resources :photos
    resources :reservations
    resources :guest_reviews
    resources :host_reviews

    root to: "users#index"
  end

  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }


  resources :users, only: [:show, :index] do
    member do

      post '/verify_phone_number' => 'users#verify_phone_number'

      patch '/update_phone_number' => 'users#update_phone_number'

      patch '/update_license' => 'users#update_license'

      patch '/update_bank_account' => 'users#update_bank_account'

      patch '/update_image' => 'users#update_image'


    end
  end


  get '/crop_image' => "users#crop_image"

  get '/certification' => "users#certification"

  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"


  resources :listings, except: [:edit] do
    member do


      get 'information'
      get 'photo_upload'
      get 'detail'
      get 'exhibition'

      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :show]
  end




  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/my_reservations' => 'reservations#my_reservations'
  get '/guest_reservations' => 'reservations#guest_reservations'

  get 'search' => 'pages#search'

  get '/ajaxsearch' => 'pages#ajaxsearch'

  get 'index' => 'pages#index'
  get 'refer' => 'pages#refer'




  # ---- AirKong ------
  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
     post '/approve' => "reservations#approve"
     post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end



  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  # オリジナル追加
  get 'about' => 'pages#about'

  get 'pages/management' => 'pages#management'
  get 'pages/guide' => 'pages#guide'
  get 'pages/legal' => 'pages#legal'
  get 'pages/rules' => 'pages#rules'
  get 'pages/policy' => 'pages#policy'
  get 'pages/host_flow' => 'pages#host_flow'
  get 'pages/guest_flow' => 'pages#guest_flow'
  get 'pages/qanda' => 'pages#qanda'



  get 'inquiry' => 'inquiry#index'
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  get 'entry' => 'entry#index'
  get 'entry/confirm' => redirect("/entry")
  get 'entry/thanks' => redirect("/entry")
  post 'entry/confirm' => 'entry#confirm'
  post 'entry/thanks' => 'entry#thanks'

  get 'apply' => 'apply#index'
  get 'apply/confirm' => redirect("/apply")
  get 'apply/thanks' => redirect("/apply")
  post 'apply/confirm' => 'apply#confirm'
  post 'apply/thanks' => 'apply#thanks'

  get 'notice' => 'pages#notice'

  resources :fees, only: [:index]
end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_footer.html.erb
<!-- footer -->
<div id="footer">

<div id="footernavi_container">
  <!--ナビゲーション-->
    <div class="row">
      <nav id="">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
          <ul >
            <li>
                <%= link_to "サーフ文庫とは", about_path %>
            </li>
            <li>
              <%= link_to "特定商取引法に基づく表記", pages_legal_path %>

            </li>

            <li>
                <%= link_to "サポーター費について", fees_path %>
            </li>
            <li>
                <%= link_to "お問合わせ", inquiry_path %>
            </li>
          </ul>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
          <ul >
            <li>
              <%= link_to "ご利用ガイド", pages_guide_path %>
            <li>
              <%= link_to "利用規約", pages_rules_path %>
            </li>
            <li>
              <%= link_to "プライバシーポリシー", pages_policy_path %>

            </li>

          </ul>
        </div>
      </nav>
   </div>

   <div class="social_logo">

       <a href="https://www.facebook.com/toollibrary.jp/">
          <svg
          id="footer_facebook"
          xmlns="http://www.w3.org/2000/svg"
          xmlns:xlink="http://www.w3.org/1999/xlink"
          viewBox="0 0 300 300">
           <path class="fill" d="M283.000,-0.000 C283.000,-0.000 17.000,-0.000 17.000,-0.000 C7.853,-0.000 -0.000,7.854 -0.000,17.000 C-0.000,17.000 -0.000,283.000 -0.000,283.000 C-0.000,292.144 7.853,300.000 17.000,300.000 C17.000,300.000 161.000,300.000 161.000,300.000 C161.000,300.000 161.000,183.000 161.000,183.000 C161.000,183.000 121.000,183.000 121.000,183.000 C121.000,183.000 121.000,139.000 121.000,139.000 C121.000,139.000 161.000,139.000 161.000,139.000 C161.000,139.000 161.000,105.000 161.000,105.000 C161.000,66.251 183.432,45.000 218.000,45.000 C234.558,45.000 249.852,46.449 254.000,47.000 C254.000,47.000 254.000,88.000 254.000,88.000 C254.000,88.000 229.000,88.000 229.000,88.000 C210.201,88.000 207.000,96.891 207.000,110.000 C207.000,110.000 207.000,139.000 207.000,139.000 C207.000,139.000 252.000,139.000 252.000,139.000 C252.000,139.000 246.000,183.000 246.000,183.000 C246.000,183.000 207.000,183.000 207.000,183.000 C207.000,183.000 207.000,300.000
           207.000,300.000 C207.000,300.000 283.000,300.000 283.000,300.000 C292.144,300.000 300.000,292.144 300.000,283.000 C300.000,283.000 300.000,17.000 300.000,17.000 C300.000,7.854 292.144,-0.000 283.000,-0.000 Z"/>
         </svg>
       </a>

   </div>

   <!-- copyright-->
   <div id="copyright">
     <address>
       <p>Copyright (C) サーフ文庫 All Rights Reserved.
       </p>
     </address>
   </div>

 </div>

</div><!-- //  div  id="footer"-->

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
      
    <% end %>

  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
   <nav class="navbar navbar-default navbar-static-top">
     <div class="header-container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>

         <div class="header-box">
           <ul>
            <li id="title" class="float-left">
              <%= link_to "サーフ文庫", root_path, class: "navbar-brand " %>
            </li>
            <li class="sentence font-md">
              <span class="orange">湘南</span>のサーフィンのシェアリングサービス
            </li>
            <li class="sentence font-sm">
              <span class="orange">湘南</span>のサーフィンの<br>シェアリングサービス
            </li>

            <script type="text/javascript">
              $(function(){
               var w = window.innerWidth;
               if (w > 480){

                 $(".font-sm").remove();

               }
               if (w <= 480){

                 $(".font-md").remove();
                 $(".font-sm").append();

               }
               console.log(w);
              });
            </script>



            <% if (user_signed_in?)%>
            <li class="header-case">
                <%= link_to notifications_path do %>
                 <i class="fa fa-bell blue"></i>
                 <span class="badge" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
                <% end %>
            </li>
            <% end %>

           </ul>

           <% if   request.path == '/search' && @arrListings.count == 0 %>
           <% else %>
            <div class="exhibit">
             <p class="text-center">
               <%= link_to  new_listing_path  do %>
                 <span class="letter">
                   出品
                 </span>
                 <br>
                 <span class="icon">
                   <i class="fa fa-camera" aria-hidden="true"></i>
                 </span>

               <% end %>

             </p>

           </div>
           <% end %>

         </div>
       </div>

       <div id="navbar" class="navbar-collapse collapse">

         <ul class="nav navbar-nav navbar-right">
           <% if (!user_signed_in?)%>
            <li>
              <%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "新規ユーザー登録", new_user_registration_path %></li>

           <% else %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">


                <%= image_tag current_user.image , class: 'img-circle avatar-small'%>
                &nbsp;
                <%= current_user.fullname %>
                &nbsp;
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "ダッシュボード", dashboard_path %>

                <li>
                  <%= link_to "貸出し", listings_path %>
                </li>
                <li>
                  <%= link_to "レンタル", my_reservations_path %>
                </li>
                <li>
                  <%= link_to "アカウント設定", edit_user_registration_path %>
                </li>
                <li>
                  <%= link_to "メッセージ一覧", conversations_path %>
                </li>

                <li role="separator" class="divider"></li>

                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

           <% end %>
         </ul>

       </div><!--/.nav-collapse -->
     </div>
   </nav>



   <!-- ダッシュボードナビゲーション -->
   <% unless !(user_signed_in?) || current_page?(root_path) || current_page?(search_path) ||  current_page?("/listings/#{params[:id]}") && !current_page?(listings_path)   %>
    <nav class="navbar dashboard">
      <div class="">
        <ul class="">
          <li <% if current_page?(dashboard_path) %> class="active" <% end %> ><%= link_to "ダッシュボード", dashboard_path %></li>

          <li <% if current_page?(listings_path) || current_page?(guest_reservations_path) || current_page?(payout_method_path)  %> class="active" <% end %> ><%= link_to "貸出し", listings_path %></li>

          <li <% if current_page?(my_reservations_path)  %> class="active" <% end %> ><%= link_to "レンタル", my_reservations_path %></li>

          <li <% if current_page?(edit_user_registration_path) ||  current_page?(certification_path) || current_page?(payment_method_path) %> class="active" <% end %> ><%= link_to "アカウント設定", edit_user_registration_path %></li>

          <li <% if current_page?(conversations_path) %> class="active" <% end %> ><%= link_to "メッセージ一覧", conversations_path %></li>

        </ul>
      </div>
    </nav>

  <% end %>