config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :conversations
    resources :reviews
    resources :listings
    resources :messages
    resources :notifications
    resources :photos
    resources :reservations
    resources :guest_reviews
    resources :host_reviews

    root to: "users#index"
  end

  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }


  resources :users, only: [:show, :index] do
    member do

      post '/verify_phone_number' => 'users#verify_phone_number'

      patch '/update_phone_number' => 'users#update_phone_number'

      patch '/update_license' => 'users#update_license'

      patch '/update_bank_account' => 'users#update_bank_account'

      patch '/update_image' => 'users#update_image'


    end
  end


  get '/crop_image' => "users#crop_image"

  get '/certification' => "users#certification"

  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"


  resources :listings, except: [:edit] do
    member do


      get 'information'
      get 'photo_upload'
      get 'detail'
      get 'exhibition'

      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :show]
  end




  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/my_reservations' => 'reservations#my_reservations'
  get '/guest_reservations' => 'reservations#guest_reservations'

  get 'search' => 'pages#search'

  get '/ajaxsearch' => 'pages#ajaxsearch'

  get 'index' => 'pages#index'
  get 'refer' => 'pages#refer'




  # ---- AirKong ------
  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
     post '/approve' => "reservations#approve"
     post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end



  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  # オリジナル追加
  get 'about' => 'pages#about'

  get 'pages/management' => 'pages#management'
  get 'pages/guide' => 'pages#guide'
  get 'pages/legal' => 'pages#legal'
  get 'pages/rules' => 'pages#rules'
  get 'pages/policy' => 'pages#policy'
  get 'pages/host_flow' => 'pages#host_flow'
  get 'pages/guest_flow' => 'pages#guest_flow'
  get 'pages/qanda' => 'pages#qanda'



  get 'inquiry' => 'inquiry#index'
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  get 'entry' => 'entry#index'
  get 'entry/confirm' => redirect("/entry")
  get 'entry/thanks' => redirect("/entry")
  post 'entry/confirm' => 'entry#confirm'
  post 'entry/thanks' => 'entry#thanks'

  get 'apply' => 'apply#index'
  get 'apply/confirm' => redirect("/apply")
  get 'apply/thanks' => redirect("/apply")
  post 'apply/confirm' => 'apply#confirm'
  post 'apply/thanks' => 'apply#thanks'

  get 'notice' => 'pages#notice'

  resources :fees, only: [:index]
end

app/models/apply.rb
class Apply
  include ActiveModel::Model

  attr_accessor :name, :email, :message, :address, :phone_number

  validates :name,  length: { minimum: 3, :too_short => '名前を入力して下さい'}
  validates :email, length: { minimum: 3, :too_short => 'メールアドレスを入力して下さい'}

end

app/controllers/apply_controller.rb
class ApplyController < ApplicationController
  # 入力画面を表示
  def index
    @apply = Apply.new
    render :action => 'index'
  end

  # 入力値のチェック
  def confirm
    @apply = Apply.new(apply_params)
    if @apply.valid?
     # OK。確認画面を表示
     render :action => 'confirm'
    else
     # NG。入力画面を再表示
     render :action => 'index'
    end
  end

  # メール送信
  def thanks
    @apply = Apply.new(apply_params)
    ApplyMailer.sent_email(@apply).deliver
    ApplyMailer.received_email(@apply).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

  private

  def apply_params
    params.require(:apply).permit(:name, :email, :message, :address, :phone_number)
  end

end

app/views/apply/confirm.html.erb
<div class="" id="entry">

<div class="entry-box" id="top">
  <ul>
   <li id="title" class="">
     <%= link_to "サーフ文庫", apply_path, class: "navbar-brand " %>
   </li>
   <li class="sentence font-md">
     副収入を得られるサーフボードロッカー
   </li>
   <li class="sentence font-sm">
     副収入を得られる<br>サーフボードロッカー
   </li>

   <script type="text/javascript">
     $(function(){
      var w = window.innerWidth;
      if (w > 480){

        $(".font-sm").remove();

      }
      if (w <= 480){

        $(".font-md").remove();
        $(".font-sm").append();

      }
      console.log(w);
     });
   </script>

  </ul>

</div>

<p class="animated infinite slideOutRight" id="motion">
 <span class="">🌊</span><span class="reverse" >🏄</span>
</p>

<nav class="upper">
  <div class="inform text-center">
    <p>
      今年の夏に湘南の鵠沼海岸でオープン予定<br>
      ただいま事前登録者を<span class="red"><b>先着50名</b></span>まで募集中
    </p>
  </div>
</nav>

<p class="text-center">

事前応募フォームです。<br>返信は通常24時間以内におこなっております。
</p>

<div class="row">
  <div class=" text-center frame">
    <div class="panel panel-default">
      <h3>確認画面</h3>


      <div class="container">

        <%= form_for @apply, :url => apply_thanks_path do |f| %>

        <table class="table table-bordered text-left">
         <tbody>
          <tr>
            <th scope="row">
              名前
            </th>
            <td colspan="3">
              <%= f.hidden_field :name %>
              <%= @apply.name %>
            </td>
          </tr>
          <tr>
            <th scope="row">
              メールアドレス
            </th>
            <td colspan="3">
              <%= f.hidden_field :email %>
              <%= @apply.email %>
            </td>
          </tr>
          <tr>
            <th scope="row">
              住所
            </th>
            <td colspan="3">
              <%= f.hidden_field :address %>
              <%= @apply.address %>
            </td>
          </tr>
          <tr>
            <th scope="row">
              電話番号
            </th>
            <td colspan="3">
              <%= f.hidden_field :phone_number %>
              <%= @apply.phone_number %>
            </td>
          </tr>

          <tr>
            <th scope="row">
              その他&nbsp;自由記入欄
            </th>
            <td colspan="3">
              <%= f.hidden_field :message %>
              <%= simple_format(@apply.message) %>
            </td>
          </tr>
         </tbody>
        </table>

        <div class="actions">
          <%= f.submit "送信する", class: "btn btn-form" %>
        </div>

        <% end %>

      </div>
    </div>
  </div>
</div>

</div>

app/views/apply/thanks.html.erb
<div class="" id="entry">

  <div class="entry-box" id="top">
    <ul>
     <li id="title" class="">
       <%= link_to "サーフ文庫", apply_path, class: "navbar-brand " %>
     </li>
     <li class="sentence font-md">
       副収入を得られるサーフボードロッカー
     </li>
     <li class="sentence font-sm">
       副収入を得られる<br>サーフボードロッカー
     </li>

     <script type="text/javascript">
       $(function(){
        var w = window.innerWidth;
        if (w > 480){

          $(".font-sm").remove();

        }
        if (w <= 480){

          $(".font-md").remove();
          $(".font-sm").append();

        }
        console.log(w);
       });
     </script>

    </ul>

  </div>


  <p class="animated infinite slideOutRight" id="motion">
   <span class="">🌊</span><span class="reverse" >🏄</span>
  </p>

  <nav class="upper">
    <div class="inform text-center">
      <p>
        今年の夏に湘南の鵠沼海岸でオープン予定<br>
        ただいま事前登録者を<span class="red"><b>先着50名</b></span>まで募集中
      </p>
    </div>
  </nav>

<p class="text-center">

事前応募フォームです。<br>返信は通常24時間以内に行なっております。
</p>
<div class="row">
  <div class=" text-center frame">
    <div class="panel panel-default">
      <h3>完了画面</h3>

      <h4>
        応募頂きありがとうございました!
      </h4>
    </div>
  </div>
</div>

</div>