config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :conversations
    resources :reviews
    resources :listings
    resources :messages
    resources :notifications
    resources :photos
    resources :reservations
    resources :guest_reviews
    resources :host_reviews

    root to: "users#index"
  end

  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
             controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }


  resources :users, only: [:show, :index] do
    member do

      post '/verify_phone_number' => 'users#verify_phone_number'

      patch '/update_phone_number' => 'users#update_phone_number'

      patch '/update_license' => 'users#update_license'

      patch '/update_bank_account' => 'users#update_bank_account'

      patch '/update_image' => 'users#update_image'


    end
  end


  get '/crop_image' => "users#crop_image"

  get '/certification' => "users#certification"

  get '/payment_method' => "users#payment"
  get '/payout_method' => "users#payout"
  post '/add_card' => "users#add_card"


  resources :listings, except: [:edit] do
    member do


      get 'information'
      get 'photo_upload'
      get 'detail'
      get 'exhibition'

      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create, :show]
  end




  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/my_reservations' => 'reservations#my_reservations'
  get '/guest_reservations' => 'reservations#guest_reservations'

  get 'search' => 'pages#search'

  get '/ajaxsearch' => 'pages#ajaxsearch'

  get 'index' => 'pages#index'
  get 'refer' => 'pages#refer'




  # ---- AirKong ------
  get 'dashboard' => 'dashboards#index'

  resources :reservations, only: [:approve, :decline] do
    member do
     post '/approve' => "reservations#approve"
     post '/decline' => "reservations#decline"
    end
  end

  resources :revenues, only: [:index]

  resources :conversations, only: [:index, :create]  do
    resources :messages, only: [:index, :create]
  end



  get '/notifications' => 'notifications#index'

  mount ActionCable.server => '/cable'

  # オリジナル追加
  get 'about' => 'pages#about'

  get 'pages/management' => 'pages#management'
  get 'pages/guide' => 'pages#guide'
  get 'pages/legal' => 'pages#legal'
  get 'pages/rules' => 'pages#rules'
  get 'pages/policy' => 'pages#policy'
  get 'pages/host_flow' => 'pages#host_flow'
  get 'pages/guest_flow' => 'pages#guest_flow'
  get 'pages/qanda' => 'pages#qanda'



  get 'inquiry' => 'inquiry#index'
  get 'inquiry/confirm' => redirect("/inquiry")
  get 'inquiry/thanks' => redirect("/inquiry")
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  get 'entry' => 'entry#index'
  get 'entry/confirm' => redirect("/entry")
  get 'entry/thanks' => redirect("/entry")
  post 'entry/confirm' => 'entry#confirm'
  post 'entry/thanks' => 'entry#thanks'

  get 'apply' => 'apply#index'
  get 'apply/confirm' => redirect("/apply")
  get 'apply/thanks' => redirect("/apply")
  post 'apply/confirm' => 'apply#confirm'
  post 'apply/thanks' => 'apply#thanks'

  get 'notice' => 'pages#notice'

  resources :fees, only: [:index]
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name,  length: { minimum: 3, :too_short => '名前を入力して下さい'}
  validates :email, length: { minimum: 3, :too_short => 'メールアドレスを入力して下さい'}
  validates :message, :presence => { :message => '問い合わせ内容を入力して下さい'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  # 入力画面を表示
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  # 入力値のチェック
  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
     # OK。確認画面を表示
     render :action => 'confirm'
    else
     # NG。入力画面を再表示
     render :action => 'index'
    end
  end

  # メール送信
  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.sent_email(@inquiry).deliver
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end

end

app/views/inquiry/confirm.html.erb
<p class="text-center">

サーフ文庫運営事務局へのお問い合わせフォームです。<br>お問い合わせへの返信は通常1営業日以内に行なっております。
</p>

<div class="row">
  <div class=" text-center">
    <div class="panel panel-default">
      <h3>お問合わせ確認画面</h3>


      <div class="container">

        <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>

        <table class="table table-bordered text-left">
         <tbody>
          <tr>
            <th scope="row">
              名前
            </th>
            <td colspan="3">
              <%= f.hidden_field :name %>
              <%= @inquiry.name %>
            </td>
          </tr>
          <tr>
            <th scope="row">
              メールアドレス
            </th>
            <td colspan="3">
              <%= f.hidden_field :email %>
              <%= @inquiry.email %>
            </td>
          </tr>
          <tr>
            <th scope="row">
              問い合わせ内容
            </th>
            <td colspan="3">
              <%= f.hidden_field :message %>
              <%= simple_format(@inquiry.message) %>
            </td>
          </tr>
         </tbody>
        </table>

        <div class="actions">
          <%= f.submit "送信する", class: "btn btn-form" %>
        </div>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/inquiry/index.html.erb
<p class="text-center">

サーフ文庫運営事務局へのお問い合わせフォームです。<br>お問い合わせへの返信は通常1営業日以内に行なっております。
</p>
<div class="row">
  <div class=" text-center">
    <div class="panel panel-default">
      <h3>お問合わせ窓口</h3>

      <div class="container">

        <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>

        <% if @inquiry.errors.any? %>
         <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
           <ul>
             <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
        <% end %>



        <div class="form_box">
          <p>名前</p>
          <div class="form-group">
            <%= f.text_field :name, autofocus: true, placeholder: "湘南太郎", class: "form-control" %>
          </div>
        </div>

        <div class="form_box">
          <p>メールアドレス</p>
          <div class="form-group">
            <%= f.email_field :email, autofocus: true, placeholder: "sample@gmail.com", class: "form-control" %>
          </div>
        </div>

        <div class="form_box inquiry-text">
          <p>問い合わせ内容 </p>
          <div class="form-group">
            <%= f.text_area :message, autofocus: true, class: "form-control" %>
          </div>
        </div>


        <div class="actions">
          <%= f.submit "確認する", class: "btn btn-form" %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<p class="text-center">

サーフ文庫運営事務局へのお問い合わせフォームです。<br>お問い合わせへの返信は通常1営業日以内に行なっております。
</p>
<div class="row">
  <div class=" text-center">
    <div class="panel panel-default">
      <h3>お問合わせ完了画面</h3>

      <h4>
        お問合わせ頂きありがとうございました!
      </h4>
    </div>
  </div>
</div>